"use client";

import { db } from "@/lib/firebase/firebaseClient";
import { collection, onSnapshot, orderBy, query } from "firebase/firestore";
import React, { useEffect, useState } from "react";
import { ChatType } from "@/types";
import { useAuth } from "@/context/AuthContext";
import UserAvatar from "@/app/components/UserAvatar";
import { BotMessageSquare } from "lucide-react";
import MessageDisplay from "@/app/components/MessageDisplay";

interface Message {
  id: string;
  content: string;
  sender: "user" | "ai";
  type: "text" | "audio" | "image";
  imageUrls?: string[];
}

export default function ChatMessage({
  chatId,
}: {
  chatId: string;
  chatType: ChatType;
}) {
  const [messages, setMessages] = useState<Message[]>([]);
  const { currentUser } = useAuth();

  useEffect(() => {
    if (!chatId) return;

    setMessages([]);

    const q = query(
      collection(db, "chats", chatId, "messages"),
      orderBy("created_at", "asc"),
    );

    const unsubscribe = onSnapshot(
      q,
      (snapshot) => {
        const messageMap = new Map();

        snapshot.docs.forEach((doc) => {
          const data = doc.data();
          messageMap.set(doc.id, {
            id: doc.id,
            ...data,
          });
        });

        const uniqueMessages = Array.from(messageMap.values()) as Message[];
        setMessages(uniqueMessages);
      },
      (error) => {
        console.error("Firestore Listen Error:", error);
      },
    );

    return () => unsubscribe();
  }, [chatId]);

  return (
    <div className="flex flex-col gap-y-6 p-6 min-h-full">
      {messages.map((m) => {
        const isUser = m.sender === "user";
        // content 自体に画像URLが入っているか判定（画像生成用）
        const isGeneratedImage =
          m.type === "image" && m.content.startsWith("http");

        return (
          <div
            key={m.id}
            className="flex items-start gap-x-3 w-full justify-start"
          >
            {/* アイコンエリア */}
            <div className="shrink-0 mt-1">
              {isUser ? (
                <UserAvatar
                  user={currentUser as any}
                  className="w-8 h-8 border-2 border-white shadow-sm"
                />
              ) : (
                <div className="w-8 h-8 rounded-full bg-white border border-slate-200 flex items-center justify-center shadow-sm">
                  <BotMessageSquare className="w-4 h-4 text-blue-600" />
                </div>
              )}
            </div>

            {/* 吹き出しエリア */}
            <div
              className={`p-4 rounded-2xl shadow-md border border-slate-100 bg-white text-slate-800 rounded-tl-none
              max-w-[85%] sm:max-w-[60%] md:max-w-[45%] transition-all`}
            >
              {/* 1. 【画像生成】content にURLが入っている場合 */}
              {isGeneratedImage && (
                <div className="mb-2 rounded-lg overflow-hidden border border-slate-100 shadow-sm bg-slate-50">
                  <img
                    src={m.content}
                    alt="Generated by AI"
                    className="w-full h-auto object-contain max-h-[400px]"
                  />
                </div>
              )}

              {/* 2. 【通常テキスト・画像解析・音声】 */}
              <MessageDisplay
                // 生成画像の場合は content (URL) を表示せず、空文字を渡す
                markdown={isGeneratedImage ? "" : m.content}
                type={m.type}
                imageUrls={m.imageUrls}
              />
            </div>
          </div>
        );
      })}
    </div>
  );
}
