"use client";

import { db } from "@/lib/firebase/firebaseClient";
import { collection, onSnapshot, orderBy, query } from "firebase/firestore";
import React, { useEffect, useState } from "react";
import { ChatType } from "@/types";
import { useAuth } from "@/context/AuthContext";
import UserAvatar from "@/app/components/UserAvatar";
import { BotMessageSquare, Mic } from "lucide-react";
import MessageDisplay from "@/app/components/MessageDisplay";

interface Message {
  id: string;
  content: string;
  sender: "user" | "ai";
  type: "text" | "audio" | "image";
  imageUrls?: string[];
}

export default function ChatMessage({
  chatId,
}: {
  chatId: string;
  chatType: ChatType;
}) {
  const [messages, setMessages] = useState<Message[]>([]);
  const { currentUser } = useAuth();

  useEffect(() => {
    if (!chatId) return;

    setMessages([]);

    const q = query(
      collection(db, "chats", chatId, "messages"),
      orderBy("created_at", "asc"),
    );

    const unsubscribe = onSnapshot(
      q,
      (snapshot) => {
        const messageMap = new Map();

        snapshot.docs.forEach((doc) => {
          const data = doc.data();
          messageMap.set(doc.id, {
            id: doc.id,
            ...data,
          });
        });

        const uniqueMessages = Array.from(messageMap.values()) as Message[];
        setMessages(uniqueMessages);
      },
      (error) => {
        console.error("Firestore Listen Error:", error);
      },
    );

    return () => unsubscribe();
  }, [chatId]);

  return (
    <div className="flex flex-col gap-y-6 p-6 min-h-full">
      {messages.map((m) => {
        const isUser = m.sender === "user";

        // 画像生成の判定
        const isGeneratedImage =
          m.type === "image" && m.content.startsWith("http");

        // 音声データの判定
        const isAudioResponse =
          m.type === "audio" && m.content.startsWith("http");

        return (
          <div
            key={m.id}
            className="flex items-start gap-x-3 w-full justify-start"
          >
            {/* アイコンエリア */}
            <div className="shrink-0 mt-1">
              {isUser ? (
                <UserAvatar
                  user={currentUser as any}
                  className="w-8 h-8 border-2 border-white shadow-sm"
                />
              ) : (
                <div className="w-8 h-8 rounded-full bg-white border border-slate-200 flex items-center justify-center shadow-sm">
                  <BotMessageSquare className="w-4 h-4 text-blue-600" />
                </div>
              )}
            </div>

            {/* 吹き出しエリア */}
            <div
              className={`p-4 rounded-2xl shadow-md border border-slate-100 bg-white text-slate-800 rounded-tl-none
              max-w-[85%] sm:max-w-[60%] md:max-w-[50%] transition-all`}
            >
              {/* 【画像生成表示】 */}
              {isGeneratedImage && (
                <div className="mb-2 rounded-lg overflow-hidden border border-slate-100 shadow-sm bg-slate-50">
                  <img
                    src={m.content}
                    alt="Generated by AI"
                    className="w-full h-auto object-contain max-h-[400px]"
                  />
                </div>
              )}

              {/* 【テキスト表示】 */}
              <MessageDisplay
                markdown={isGeneratedImage || isAudioResponse ? "" : m.content}
                // 音声レスポンスの場合は "text" として渡すことで、MessageDisplay 側の二重表示を防止
                type={isAudioResponse ? "text" : m.type}
                imageUrls={m.imageUrls}
              />

              {/* 【音声プレーヤー表示】★こちらを優先して表示 */}
              {isAudioResponse && (
                <div className="mt-2 p-3 bg-slate-50 rounded-xl border border-slate-100">
                  <div className="flex items-center gap-2 mb-2 text-xs font-bold text-slate-500">
                    <Mic size={14} className="text-blue-500" />
                    AI Voice Response
                  </div>
                  <audio
                    src={m.content}
                    controls
                    className="w-full h-10 min-w-[200px]"
                  >
                    お使いのブラウザは音声再生に対応していません。
                  </audio>
                </div>
              )}
            </div>
          </div>
        );
      })}
    </div>
  );
}
